### ISSUE TITLE
bug: app crashing on back gesture on android

### ISSUE THREAD

**Issue by chadmorrow** [mozzius/graysky#59]
### Describe the bug

The app crashes when you've tapped into a thread and then use a gesture to go back. It doesn't happen every time but it happens often enough that I can reproduce it in under a minute. I hooked up logcat to my device to try and catch the problem and here's the relevant capture:

```
09-25 10:13:49.552 24937 24937 E InputEventReceiver: Exception dispatching input event.
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI: com.facebook.jni.CppException: Exception in HostFunction: Incompatible object passed to scheduleOnJS. It is only allowed to schedule functions defined on the React Native JS runtime this way.
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI: 
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI: Error: Exception in HostFunction: Incompatible object passed to scheduleOnJS. It is only allowed to schedule functions defined on the React Native JS runtime this way.
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:     at _scheduleOnJS (native)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:     at anonymous (JavaScript:1:192)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:     at anonymous (JavaScript:1:211)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:     at anonymous (JavaScript:1:628)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:     at handleAndFlushAnimationFrame (JavaScript:1:147)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(Native Method)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java:25)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.kt:42)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:309)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:285)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.ReactContextExtensionsKt.dispatchEvent(ReactContextExtensions.kt:9)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForDirectEvent(RNGestureHandlerModule.kt:638)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForReanimated(RNGestureHandlerModule.kt:624)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onStateChange(RNGestureHandlerModule.kt:576)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$onStateChange(RNGestureHandlerModule.kt:38)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerModule$eventListener$1.onStateChange(RNGestureHandlerModule.kt:346)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandler.dispatchStateChange(GestureHandler.kt:84)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.kt:157)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandler.moveToState(GestureHandler.kt:551)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandler.cancel(GestureHandler.kt:640)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.cancelAll(GestureHandlerOrchestrator.kt:246)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.kt:43)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.kt:97)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.kt:35)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.View.dispatchPointerEvent(View.java:15309)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.os.MessageQueue.nativePollOnce(Native Method)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.os.MessageQueue.next(MessageQueue.java:335)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.os.Looper.loopOnce(Looper.java:161)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.os.Looper.loop(Looper.java:288)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at android.app.ActivityThread.main(ActivityThread.java:7918)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at java.lang.reflect.Method.invoke(Native Method)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-25 10:13:49.552 24937 24937 E MessageQueue-JNI:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Which maybe points the finger at Reanimated but from working on my own Expo apps in the past, that might just be a red herring and the actual issue may be elsewhere, possibly in Expo Router? 

### To reproduce

Using a Pixel 6 Pro device, navigate to a feed and then tap into any thread, then attempt to go back by using a swipe gesture. 

### Additional information

 Phone model is Pixel 6 Pro, Android version 13

**Comment by mozzius** [comment]
Fixed in a previous version
